"Food":'fdc_id','data_type', 'description'
Where the fdc_id is the unique permament identifier of a food in the food table

Agricultural adquisition: Non-processed foods obtained directly from the location where they are produced

branded food: Foods whose nutrient values are obtained from food label data provided by food brand owners

In [2]:
import pandas as pd
data = pd.read_csv('../data/raw/FoodData_Central_csv_2023-04-20/food.csv')

In [18]:
data

,fdc_id,data_type,description,food_category_id,publication_date
0,1105904,branded_food,WESSON Vegetable Oil 1 GAL,NaN,2020-11-13
1,1105905,branded_food,SWANSON BROTH BEEF,NaN,2020-11-13
2,1105906,branded_food,CAMPBELL'S SLOW KETTLE SOUP CLAM CHOWDER,NaN,2020-11-13
3,1105907,branded_food,CAMPBELL'S SLOW KETTLE SOUP CHEESE BROCCOLI,NaN,2020-11-13
4,1105898,experimental_food,Discrepancy between the Atwater factor predict...,NaN,2020-10-30
...,...,...,...,...,...
1913734,2554910,branded_food,"CHEF SALAD FRESH GREENS, RANCH DRESSING, TOMAT...",NaN,2023-05-25
1913735,2554911,branded_food,"PINEAPPLE COCONUT WATER, PINEAPPLE",NaN,2023-05-25
1913736,2554912,branded_food,DELICIOUS & NUTRITIOUS WHOLE MILK,NaN,2023-05-25
1913737,2554913,branded_food,"CAULIFLOWER BURGERS, CAULIFLOWER",NaN,2023-05-25
1913738,2554914,branded_food,"MARCONA ALMONDS WITH TRUFFLE SALT, TRUFFLE SALT",NaN,2023-05-25